config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  root to: 'events#index'

  get 'user', to: 'users#show'
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :events

  resources :event_attendees, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ActiveRecord::Base
  scope :past, -> { where('event_date < ?', Date.today) }
  scope :upcoming, -> { where('event_date >= ?', Date.today) }

  validates :event_date, :event_name, :description, presence: true
  validates :description, length: { minimum: 10 }

  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_many :event_attendees, dependent: :destroy
  has_many :attendees, through: :event_attendees, source: :user
end

app/models/event_attendee.rb
class EventAttendee < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  validates :username, presence: true

  has_many :events
  has_many :event_attendees, dependent: :destroy
  has_many :attended_events, through: :event_attendees, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  before_action :authenticate_user!

  def new
    @event_attendee = EventAttendee.new
    @event_id = params[:event_id]
  end

  def create
    @event_attendee = current_user.event_attendees.build(event_attendee_params)

    if @event_attendee.save
      flash[:notice] = "Signed up for event successfully!"
      redirect_to root_path
    else
      flash.now[:alert] = "Event sign-up failed."
    end
  end

  private

  def event_attendee_params
    params.require(:event_attendee).permit(:event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user, only: [:edit, :update, :destroy]
  
  def index
    @events = Event.all
    @upcoming_events = Event.upcoming
    @past_events = Event.past
  end

  def show
    @event = Event.find(params[:id])
    @attendees = find_attendees
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      flash[:notice] = "Event created successfully"
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      flash[:notice] = "Event updated successfully!"
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    flash[:notice] = "Event deleted successfully"
    redirect_to root_path
  end

  private

  def event_params
    params.require(:event).permit(:event_date, :event_name, :description)
  end

  def authorize_user
    event = Event.find(params[:id])

    unless current_user.id == event.user_id
      flash[:alert] = "You do not have permission to modifiy this event"
      redirect_to root_path
    end
  end

  def find_attendees
    attendees = []
    event_attendees = EventAttendee.where(event_id: @event.id)

    event_attendees.each do |record|
      attendees << User.find(record.user_id).username
    end

    attendees
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  private

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  
  def show
    @created_events = current_user.events
    @events = attending_events
    @upcoming_events = @events.select { |event| event.event_date >= Date.today }
    @past_events = @events.select { |event| event.event_date < Date.today }
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out sucessfully."
    redirect_to root_path
  end

  private

  def attending_events
    events = []
    my_events = EventAttendee.where(user_id: current_user.id)

    my_events.each do |event|
      events << Event.find(event.event_id)
    end

    events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_attendees/new.html.erb
<% event = Event.find(@event_id) %>
<h1><%= event.event_name %> sign-up</h1>

<p>Click the button below to confirm your attendence!</p>

<%= form_with model: @event_attendee, url: event_attendees_path do |f| %>
  <%= f.hidden_field :event_id, value: @event_id %>
  <%= f.submit 'Confirm attendence' %>
<% end %>

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <% if @event.errors.any? %>
    <div style="color: red;">
      <h2><%= pluralize(@event.errors.count, "error") %> Prohibited this event from being saved:</h2>
    </div>

    <ul>
      <% @event.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :event_name, 'Event Name:' %>
    <%= f.text_field :event_name %>
  </div>
  <div>
    <%= f.label :description, 'Summary:' %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.label :event_date, 'Date:' %>
    <%= f.date_field :event_date %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<h1>Events Home</h1>

<hr><br>

<%= render partial: 'shared/event_partial' %>

<%= render partial: 'shared/login_partial' %>

app/views/events/new.html.erb
<h1>Create Event</h1>

<%= form_for @event do |f| %>
  <% if @event.errors.any? %>
    <div style="color: red;">
      <h2><%= pluralize(@event.errors.count, "error") %> Prohibited this event from being saved:</h2>
    </div>

    <ul>
      <% @event.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :event_name, 'Event Name:' %>
    <%= f.text_field :event_name %>
  </div>
  <div>
    <%= f.label :description, 'Summary:' %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.label :event_date, 'Date:' %>
    <%= f.date_field :event_date %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.event_name %></h1>
<p><strong>Summary:</strong> <%= @event.description %></p>
<p><strong>Date:</strong> <%= @event.event_date %></p>
<p>
  <strong>Attendees:</strong>
  <ul style="list-style-type: none;">
    <% @attendees.each do |user| %>
      <li><%= user %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Attend event', new_event_attendee_path(event_id: @event.id) %><br>

<%= render partial: 'shared/login_partial' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <%= link_to 'Home', root_path %>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert" style="color: red;"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_event_partial.html.erb
<% if @past_events.any? %>
  <h3>Past events</h3>

  <hr><br>

  <% @past_events.each do |event| %>
    <div style="padding-left: 1rem; border: 1px solid black;">
      <h3><%= event.event_name %></h3>
      <%= link_to 'Show details', event_path(event) %><br><br>
    </div>
  <% end %>
<% end %>

<% if @upcoming_events.any? %>
  <h3>Upcoming Events</h3>

  <hr><br>

  <% @upcoming_events.each do |event| %>
    <div style="padding-left: 1rem; border: 1px solid black;">
      <h3><%= event.event_name %></h3>
      <%= link_to 'Show details', event_path(event) %><br><br>
    </div>
  <% end %>
<% end %>

app/views/shared/_login_partial.html.erb
<% if current_user %>
  <br><%= link_to 'Your events', user_path %><br>
  <br><%= button_to 'Logout', destroy_user_session_path, method: :delete %>
<% else %>
  <br><%= link_to 'Log in', new_user_session_path %>
<% end %>

app/views/users/show.html.erb
<h1><%= current_user.username %> Events</h1>

<hr><br>

<h2>Created Events</h2>

<% @created_events.each do |event| %>
  <div style="padding-left: 1rem; border: 1px solid black;">
    <h2><%= event.event_name %></h2>
    <%= link_to 'Show details', event_path(event) %><br><br>
    <%= button_to 'Delete Event', event_path(event), method: :delete, data: { turbo_confirm: 'Are you sure you want to delete this event?' } %><br>
  </div>
<% end %>

<br><%= link_to 'Create new event', new_event_path %><br><br>

<h2>Saved Events</h2>

<%= render partial: 'shared/event_partial' %>